# Generated by Django 3.1.2 on 2021-01-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yunpan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('离校日期', models.DateField()),
                ('目的地', models.CharField(max_length=200)),
                ('交通工具', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Reporter',
            new_name='Name',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='information',
            name='姓名',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yunpan.name'),
        ),
    ]
