# Generated by Django 3.1.2 on 2021-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201123_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='headline',
            new_name='交通工具',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='student',
            new_name='姓名',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='commit_date',
            new_name='离校日期',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='attach',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='remark',
        ),
        migrations.AddField(
            model_name='homework',
            name='目的地',
            field=models.CharField(default='省份', max_length=200),
        ),
    ]
