# Generated by Django 3.1.2 on 2021-01-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210110_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='学号',
            field=models.CharField(default='填写学号', max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='', max_length=70, verbose_name='姓名'),
        ),
    ]
