# Generated by Django 3.1.2 on 2021-01-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210112_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='交通工具',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(default='', max_length=70, verbose_name='姓名')),
            ],
        ),
    ]
