# Generated by Django 3.1.2 on 2021-01-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210112_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='交通工具',
            field=models.CharField(default='方式', max_length=200),
        ),
    ]
