# Generated by Django 3.1.2 on 2021-01-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210112_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='交通工具',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.交通工具'),
        ),
    ]
