# Generated by Django 3.1.2 on 2021-01-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210112_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='学生信息',
        ),
   
      
    ]
