# Generated by Django 3.1.2 on 2021-01-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210112_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='班级',
            field=models.CharField(default='填写班级', max_length=20),
        ),
        migrations.AddField(
            model_name='学生信息',
            name='IP',
            field=models.CharField(default='', max_length=13, verbose_name='学号'),
        ),
    ]
