# Generated by Django 3.1.2 on 2021-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210112_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='学生信息',
            name='condition',
            field=models.IntegerField(choices=[(1, '健康'), (2, '有症状'), (3, '其他')]),
        ),
    ]
